# Generated by Django 3.1.5 on 2021-01-20 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(max_length=2000, verbose_name='テキスト')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('author', models.ForeignKey(default='退会済みのユーザー', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=500, verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('name', models.ForeignKey(default='退会済みのユーザー', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='対象記事')),
            ],
        ),
    ]
